import { mkdir, cp, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

async function build() {
  console.log('🏗️  Building LucaSchema...');

  try {
    const distEsm = join(root, 'dist/esm');

    await mkdir(distEsm, { recursive: true });

    // Copy schemas to ESM destination
    await cp(join(root, 'src/schemas'), join(distEsm, 'schemas'), {
      recursive: true
    });

    // Copy ESM entrypoints
    await cp(join(root, 'src', 'index.js'), join(distEsm, 'index.js'));
    await cp(join(root, 'src', 'enums.js'), join(distEsm, 'enums.js'));
    await cp(
      join(root, 'src', 'lucaValidator.js'),
      join(distEsm, 'lucaValidator.js')
    );

    // Copy TypeScript definitions from root dist to ESM output (generated by generate-types)
    await cp(join(root, 'dist/index.d.ts'), join(distEsm, 'index.d.ts'));

    // Create package.json for ESM subpath
    await writeFile(
      join(distEsm, 'package.json'),
      JSON.stringify({ type: 'module' }, null, 2)
    );

    console.log('✅ Build completed successfully!');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

build();
